FROM golang:latest

ENV GO111MODULE=on

# Copy all the module and workspace files
WORKDIR /app
COPY ./app/go.work .
COPY ./app/go.work.sum .

WORKDIR /app/admin
COPY ./app/admin/go.mod .
COPY ./app/admin/go.sum .

WORKDIR /app/app
COPY ./app/app/go.mod .
COPY ./app/app/go.sum .

WORKDIR /app/shared
COPY ./app/shared/go.mod .
COPY ./app/shared/go.sum .

# Download all the dependencies
WORKDIR /app/admin
RUN go mod download

WORKDIR /app/app
RUN go mod download

WORKDIR /app/shared
RUN go mod download

# Copy the source code and run the code
WORKDIR /app
COPY ./app .

WORKDIR /app/app
RUN go install github.com/gravityblast/fresh@8d1fef547a99be2395e7587f8de5d01265176650

CMD ["fresh"]