version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      - REDIS_POOL_SIZE=10
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=redis_password
      - SESSION_SECRET=secret
      - RP_ID=localhost
      - RP_DISPLAY_NAME=Blacksmith Labs
      - RP_ORIGINS=http://localhost:5173 # where the UI POC is running
      - APP_PORT=8081
    volumes:
      - ./app:/app
    ports:
      - 8081:8081
    depends_on:
      - redis
  redis:
    image: redis:latest
    command: redis-server --requirepass "redis_password"
    # volumes:
    #   - ./dev-data/redis:/data
    ports:
      - 6379:6379
