FROM golang:latest

ENV GO111MODULE=on

# Copy all the module and workspace files
WORKDIR /app
COPY ./src/go.work .
COPY ./src/go.work.sum .

WORKDIR /app/admin
COPY ./src/admin/go.mod .
COPY ./src/admin/go.sum .

WORKDIR /app/app
COPY ./src/app/go.mod .
COPY ./src/app/go.sum .

WORKDIR /app/shared
COPY ./src/shared/go.mod .
COPY ./src/shared/go.sum .

# Download all the dependencies
WORKDIR /app/admin
RUN go mod download

WORKDIR /app/app
RUN go mod download

WORKDIR /app/shared
RUN go mod download

# Copy the source code and run the code
WORKDIR /app
COPY ./src .

WORKDIR /app/app
RUN go install github.com/gravityblast/fresh@8d1fef547a99be2395e7587f8de5d01265176650

CMD ["fresh"]
