// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package credentials

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WebauthnCredential struct {
	CredentialID    []byte
	UserID          pgtype.Int8
	UseCounter      int32
	PublicKey       []byte
	AttestationType pgtype.Text
	Transport       []byte
	Flags           []byte
	Authenticator   []byte
	Attestation     []byte
	Meta            []byte
}

type WebauthnUser struct {
	ID          int64
	RefID       string
	RawID       []byte
	Name        string
	DisplayName string
}
